apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pypi-mirrors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pypi-mirrors-back
    spec:
      containers:
      - name: pypi-mirrors-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: pypi-mirrors-back
spec:
  ports:
  - port: 6379
  selector:
    app: pypi-mirrors-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pypi-mirrors-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: pypi-mirrors-front
    spec:
      containers:
      - name: pypi-mirrors-front
        image: wtfcontainerregistry.azurecr.io/pypi-mirrors:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "pypi-mirrors-back"
---
apiVersion: v1
kind: Service
metadata:
  name: pypi-mirrors-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pypi-mirrors-front
